export { default as Navbar } from './Navbar'
// export { default as BigCursor } from './BigCursor'
export { default as SimpleSlider } from './Carouse'
export { default as Seo } from './seo'
export { default as FeaturedProducts } from './FeaturedProducts'
export { default as CommonHead } from './CommonHead'
export { default as Footer } from './Footer'
export { default as Container } from './Container'
export { default as FooterCard } from './FooterCard'
export { default as Mailing } from './Mailing'
export { default as Layout } from './Layout'
export { default as LineAnimate } from './LineAnimate'
export { default as BlogCard } from './blog-card'
export { default as BlogCardAlt } from './BlogCardAlt'
export { default as Quotes } from './Quotes'
export { default as Triple } from './Triple'
export { default as HeroButtons } from './HeroButtons'
export { default as useWindowSize } from './useWindowSize'
export { default as usePaginate } from './usePaginate'
 